### ISSUE TITLE
URL in repository description links to wrong Docker image

### ISSUE THREAD

**Issue by LordChunk** [simple-login/simplelogin-postfix-docker#18]
The URL in the description of the repository currently links to the Docker repo of the forked repository instead of Simple Login's one.
![image](https://user-images.githubusercontent.com/23651869/186997069-cef5c47f-0eaa-4dab-a687-9f94069fffd7.png)

**Comment by nguyenkims** [comment]
Currently we haven't uploaded an official image for this repo yet so it's normal that it still points to the original image :)

**Comment by rehanone** [comment]
@nguyenkims , I believe we are now in a state where we can call this image to be official. I am using this for a over a year now without any issues. So I think we can update the link to https://hub.docker.com/r/simplelogin/postfix. It is also misleading to point to the original image as that is not maintained anymore.

**Comment by nguyenkims** [comment]
@rehanone this indeed makes sense, I just updated the link :)

**Comment by rehanone** [comment]
@nguyenkims , Thanks! I will close this issue as it is fixed now.
