### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by MyUncleSam** [simple-login/simplelogin-postfix-docker#28]
Hi there,

I tried this image and it worked. The only thing to mention is, that if you send to an unknown email address, the server accepts the mail. After this it sends a completely new mail back to the sender with an "Undelivered Mial Returned to Sender". As fas as I know this is called "bounce".

Is there a way to fix that? After googling it seems to be fixed by changing the bounce in the master.cf - but I cannot change it because it needs to be generated during start.

**Comment by rehanone** [comment]
Closing this issue due to lack of explanation and age of this issue. If you still this is is a problem please open a new issue and provide clear explanation of the issue.
