### ISSUE TITLE
disable cron when TLS_KEY_FILE is set

### ISSUE THREAD

**Issue by Slevin90** [simple-login/simplelogin-postfix-docker#36]
I have set a custom
TLS_KEY_FILE and TLS_CERT_FILE,  this should **disable** letsencrypt

however, every hour I get an email:
> Missing command line flags. For non-interactive execution, you will need to specify a plugin on the command line.  Run with '--help plugins' to see a list of options, and see https://eff.org/letsencrypt-plugins for more detail on what the plugins do and how to use them.
> run-parts: /etc/periodic/hourly/renew-postfix-tls: exit status 1

This renew-postfix-tls should be removed /not run if one of the .env variables (TLS_KEY_FILE / TLS_CERT_FILE) is set.

for the moment as workaround I have manually deleted the _renew-postfix-tls_ file in my container.

**Comment by Slevin90** [comment]
looks like some things in this push can be used/optimized
https://github.com/simple-login/simplelogin-postfix-docker/pull/13

**Comment by rehanone** [comment]
@Slevin90 , can you please try the #39 and see if it fixes the issue? I think it should stop the cron from running but I have not tested it. Thanks

**Comment by Slevin90** [comment]
> @Slevin90 , can you please try the #39 and see if it fixes the issue? I think it should stop the cron from running but I have not tested it. Thanks

I´ll let you know in the next days

**Comment by Slevin90** [comment]
Updated, had it running for a couple of hours an no hourly emails anymore. 

Thanks for the fix!🙌
