### ISSUE TITLE
dkim support

### ISSUE THREAD

**Issue by Slevin90** [simple-login/simplelogin-postfix-docker#37]
Sending mails via this postfix gives me bad dkim score.
keys are setup in the app-ci,  but there is no dkim in this postfix setup.

Or is the mistake in my configuration?

**Comment by Slevin90** [comment]
Never mind, found my issue on dkim testing..

**Comment by rubencm** [comment]
Was it related to https://github.com/simple-login/app/issues/2165 ?
How did you fix it?
