### ISSUE TITLE
hash & btree unsupported!

### ISSUE THREAD

**Issue by mhhakim** [simple-login/simplelogin-postfix-docker#7]
Hi,
I am trying to run this after building the docker image in my system. Looks like the hash & btree no longer supported. After some searching, I found the replacement is lmdb. After replacing hash & btree with lmdb, I am getting `error: open database /etc/aliases.lmdb: No such file or directory` this error now.

**With hash & btree:**
<pre>
Jun 09 17:23:21 mail postfix/postfix-script[79]: starting the Postfix mail system
Jun 09 17:23:21 mail postfix/master[80]: daemon started -- version 3.5.10, configuration /etc/postfix
Jun 09 17:23:27 mail postfix/smtpd[84]: error: unsupported dictionary type: hash
Jun 09 17:23:27 mail postfix/tlsmgr[86]: error: unsupported dictionary type: btree
Jun 09 17:23:27 mail postfix/tlsmgr[86]: error: unsupported dictionary type: btree
Jun 09 17:23:27 mail postfix/tlsmgr[86]: warning: btree:/var/lib/postfix/smtpd_scache is unavailable. unsupported dictionary type: btree
Jun 09 17:23:27 mail postfix/tlsmgr[86]: warning: btree:/var/lib/postfix/smtp_scache is unavailable. unsupported dictionary type: btree
Jun 09 17:23:27 mail postfix/smtpd[84]: connect from sl-postfix_sut_1.sl-network[240.0.0.6]
Jun 09 17:23:27 mail postfix/smtpd[84]: disconnect from sl-postfix_sut_1.sl-network[240.0.0.6] quit=1 commands=1
Jun 09 17:25:22 mail postfix/smtpd[87]: error: unsupported dictionary type: hash
Jun 09 17:25:22 mail postfix/smtpd[87]: connect from sl-postfix_sut_1.sl-network[240.0.0.6]
Jun 09 17:25:22 mail postfix/smtpd[87]: disconnect from sl-postfix_sut_1.sl-network[240.0.0.6] quit=1 commands=1
</pre>

**After replacing with lmdb:**
<pre>
sl-postfix    | Jun 09 17:34:16 mail postfix/postfix-script[78]: starting the Postfix mail system
sl-postfix    | Jun 09 17:34:16 mail postfix/master[79]: daemon started -- version 3.5.10, configuration /etc/postfix
sl-postfix    | Jun 09 17:34:22 mail postfix/smtpd[83]: error: open database /etc/aliases.lmdb: No such file or directory
sl-postfix    | Jun 09 17:34:22 mail postfix/smtpd[83]: connect from sl-postfix_sut_1.sl-network[240.0.0.6]
sl-postfix    | Jun 09 17:34:22 mail postfix/smtpd[83]: disconnect from sl-postfix_sut_1.sl-network[240.0.0.6] quit=1 commands=1
sut_1         | 220 app.example.com ESMTP Postfix
</pre>

I don't know how to fix the new error. Can someone please update the code base to make the image compatible with lmdb?

Thanks

**Comment by smargold476** [comment]
Hi @mhhakim 
I run into the same issue, could you tell how you moved from hash&btree to lmdb?

Regards
